<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="lmemf_base" nsURI="http://incquerylabs.com/iot/leapmotion/lmemf_base"
    nsPrefix="lmemf_base">
  <eClassifiers xsi:type="ecore:EClass" name="LMElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="valid" lowerBound="1" eType="ecore:EDataType platform:/resource/org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Vector" eSuperTypes="#//LMElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="x" lowerBound="1" eType="ecore:EDataType platform:/resource/org.eclipse.emf.ecore/model/Ecore.ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="y" lowerBound="1" eType="ecore:EDataType platform:/resource/org.eclipse.emf.ecore/model/Ecore.ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="z" lowerBound="1" eType="ecore:EDataType platform:/resource/org.eclipse.emf.ecore/model/Ecore.ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="magnitude" lowerBound="1"
        eType="ecore:EDataType platform:/resource/org.eclipse.emf.ecore/model/Ecore.ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="magnitudeSquared" lowerBound="1"
        eType="ecore:EDataType platform:/resource/org.eclipse.emf.ecore/model/Ecore.ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pitch" lowerBound="1" eType="ecore:EDataType platform:/resource/org.eclipse.emf.ecore/model/Ecore.ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="roll" lowerBound="1" eType="ecore:EDataType platform:/resource/org.eclipse.emf.ecore/model/Ecore.ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="yaw" lowerBound="1" eType="ecore:EDataType platform:/resource/org.eclipse.emf.ecore/model/Ecore.ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="normalized" lowerBound="1"
        eType="#//Vector" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="opposite" lowerBound="1"
        eType="#//Vector" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LMList" abstract="true">
    <eTypeParameters name="T">
      <eBounds eClassifier="#//LMElement"/>
    </eTypeParameters>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="empty" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="count" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
        containment="true">
      <eGenericType eTypeParameter="#//LMList/T"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ArrangementList" abstract="true">
    <eTypeParameters name="T">
      <eBounds eClassifier="#//LMElement"/>
    </eTypeParameters>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rightmost" lowerBound="1"
        containment="true">
      <eGenericType eTypeParameter="#//ArrangementList/T"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="leftmost" lowerBound="1"
        containment="true">
      <eGenericType eTypeParameter="#//ArrangementList/T"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="frontmost" lowerBound="1"
        containment="true">
      <eGenericType eTypeParameter="#//ArrangementList/T"/>
    </eStructuralFeatures>
    <eGenericSuperTypes eClassifier="#//LMList">
      <eTypeArguments eTypeParameter="#//ArrangementList/T"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Identifiable" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType platform:/resource/org.eclipse.emf.ecore/model/Ecore.ecore#//ELong"
        iD="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Matrix" eSuperTypes="#//LMElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="xBasis" lowerBound="1"
        eType="#//Vector" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="yBasis" lowerBound="1"
        eType="#//Vector" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="zBasis" lowerBound="1"
        eType="#//Vector" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="origin" lowerBound="1"
        eType="#//Vector" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rigidInverse" lowerBound="1"
        eType="#//Matrix" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DirectionalElement" abstract="true"
      eSuperTypes="#//LMElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="direction" lowerBound="1"
        eType="#//Vector" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CenterableElement" abstract="true" eSuperTypes="#//LMElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="center" lowerBound="1"
        eType="#//Matrix" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OrientationalElement" abstract="true"
      eSuperTypes="#//DirectionalElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="basis" lowerBound="1" eType="#//Matrix"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MeasurableElement" abstract="true" eSuperTypes="#//LMElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="length" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="width" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"
        defaultValueLiteral="0.0"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VisibleElement" abstract="true" eSuperTypes="#//LMElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="timeVisible" lowerBound="1"
        eType="ecore:EDataType platform:/resource/org.eclipse.emf.ecore/model/Ecore.ecore#//EFloat"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Pointable" abstract="true" eSuperTypes="#//DirectionalElement #//Identifiable #//MeasurableElement #//VisibleElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="frame" lowerBound="1" eType="ecore:EClass lmemf.ecore#//Frame"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hand" lowerBound="1" eType="ecore:EClass lmemf.ecore#//Hand"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="extended" lowerBound="1"
        eType="ecore:EDataType platform:/resource/org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="finger" lowerBound="1"
        eType="ecore:EDataType platform:/resource/org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"
        defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tool" lowerBound="1" eType="ecore:EDataType platform:/resource/org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="stabilizedTipPosition"
        lowerBound="1" eType="#//Vector" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tipPosition" lowerBound="1"
        eType="#//Vector" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tipVelocity" lowerBound="1"
        eType="#//Vector" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="touchZone" lowerBound="1"
        eType="ecore:EEnum lmemf.ecore#//PointableZone"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="touchDistance" lowerBound="1"
        eType="ecore:EDataType platform:/resource/org.eclipse.emf.ecore/model/Ecore.ecore#//EFloat"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PointableList" abstract="true">
    <eTypeParameters name="T">
      <eBounds eClassifier="#//Pointable"/>
    </eTypeParameters>
    <eStructuralFeatures xsi:type="ecore:EReference" name="extended" upperBound="-1"
        containment="true">
      <eGenericType eTypeParameter="#//PointableList/T"/>
    </eStructuralFeatures>
    <eGenericSuperTypes eClassifier="#//ArrangementList">
      <eTypeArguments eTypeParameter="#//PointableList/T"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LMContainer">
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
        eType="#//LMElement" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
