//created on: Aug 11, 2016
package rules

import com.leapmotion.leap.Frame;
import com.leapmotion.leap.Finger;
import com.leapmotion.leap.Finger.Type;

//list any import classes here.

declare Frame
	@role(event)
end

declare Finger
	@role(event)
end

declare window FrameEvents
	Frame() over window:time( 200ms ) from entry-point "FrameStream"
end

//declare any global variables here

rule "Grab gesture"
    when
        $A1 : Frame( fingers.extended().count() == 5 ) from window FrameEvents
        $A2 : Frame( fingers.extended().count() == 0, this after [ 50ms ] $A1 ) from window FrameEvents
    then
        System.out.println("GRAB!");
end

