//created on: Aug 11, 2016
package rules

import com.leapmotion.leap.Frame;
import com.leapmotion.leap.Finger;
import com.leapmotion.leap.Finger.Type;
import java.util.Date;

declare Frame
	@role(event)
end

declare Finger
	@role(event)
end

declare window FrameEvents
	Frame() over window:time( 2s ) from entry-point "FrameStream"
end

global java.util.List accepted_grabs

rule "Grab gesture"
    when
        $A1 : Frame( fingers.extended().count() == 5 ) from window FrameEvents
        $A2 : Frame( fingers.extended().count() == 0, this after $A1 ) from window FrameEvents
    then
        if(accepted_grabs.isEmpty() || $A2.timestamp() - ((Frame)accepted_grabs.get(0)).timestamp() > 2000000) {
	        System.out.println("GRAB! " + new Date($A2.timestamp() / 1000).toLocaleString());
	        accepted_grabs.add(0, $A2);
        }
end
